#!/bin/bash

module=$1
base_dir=$2
dv_versions=$3
expected_args=3

if [ $# -ne $expected_args ]
then
  echo "Usage: `basename $0` Module BaseDir DvVersions"
  exit 2
fi

for ver in $dv_versions
do
  InstallDooSoftwareProjectSingleDVVersion $module $ver $base_dir
done
