#!/bin/bash

#trap catch_errors ERR

if [[ -z $ROOTVERS && -z $(command -v root-config) ]]; then
  echo "ROOT version not set. Cannot load DooSoftware."
  return
elif [[ -z $ROOTVERS && -n $(command -v root-config) ]]; then
  export ROOTVERS=$(root-config --version | tr "/" ".")
fi

echo "Loading DooSoftware for ROOT $ROOTVERS"

export DOOFITSYS=/doosoft/doofit/ROOT_v$ROOTVERS
export DOOCORESYS=/doosoft/DooCore/ROOT_v$ROOTVERS
export DOOSELECTIONSYS=/doosoft/dooselection/ROOT_v$ROOTVERS
export BOOST_ROOT=$(dirname $(echo $LD_LIBRARY_PATH | tr ":" "\n" | grep Boost))

if [ "$1" != "--ignore-local" ]; then
  if [ -e "$HOME/LocalDooSoftware.sh" ]; then
    echo "Using local LocalDooSoftware.sh to override global software."
    source ~/LocalDooSoftware.sh
  fi
fi

echo "Using Boost from: $BOOST_ROOT"
echo "Using DooFit from: $DOOFITSYS"
echo "Using DooCore from: $DOOCORESYS"
echo "Using DooSelection from: $DOOSELECTIONSYS"

export PATH=$PATH:$DOOCORESYS/bin:$DOOFITSYS/bin:$DOOSELECTIONSYS/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DOOCORESYS/lib:$DOOFITSYS/lib:$DOOSELECTIONSYS/lib


