#!/bin/bash
uuid=`uuidgen -r`

dv_version=$1
expected_args=1

if [ $# -ne $expected_args ]
then
  echo "Usage: `basename $0` DaVinciVersion"
  exit 2
fi

source /lhcb/software/tu-dortmund/LHCbSoftwareSetup.sh x86_64-slc5-gcc46-opt > /dev/null 2>&1
source SetupProject.sh DaVinci $dv_version > /dev/null 2>&1
#source LoadDooSoftware --ignore-local
#mkdir /tmp/$uuid
#cd /tmp/$uuid
#echo "Starting build"
#echo
echo $ROOTVERS


