#!/bin/bash
uuid=`uuidgen -r`

dv_version=$1
expected_args=1

if [ $# -ne $expected_args ]
then
  echo "Usage: `basename $0` DaVinciVersion"
  exit 2
fi

# source /lhcbsoft/LHCbSoftwareSetup.sh x86_64-slc6-gcc48-opt > /dev/null 2>&1
# source SetupProject.sh DaVinci $dv_version > /dev/null 2>&1
source /lhcbsoft/LHCbSoftwareSetup.sh x86_64-slc6-gcc49-opt > /dev/null 2>&1

ROOTVERS=$(lb-run DaVinci/$dv_version root-config --version | tr "/" ".")

echo $ROOTVERS
