#!/bin/bash

packages="DooCore DooFit DooSelection"

source /lhcb/software/tu-dortmund/LHCbSoftwareSetup.sh #> /dev/null 2>&1

echo "Probing ROOT versions"
rvers=""
dvvers=""
echo -n "Installing for following DaVinci versions: "
for ver in `SetupProject.sh DaVinci --list-versions | cut -d " " -f 1`
do
  rver=`bash PrintRootVersionForDVVersion $ver`
  if [[ ! $rvers =~ $rver ]]; then
    rvers="$rvers $rver"
    dvvers="$dvvers $ver"
    echo -n " $ver"
  fi
done
echo ""

for p in $packages; do
  dir=$DOOSOFTROOT/repos/$p
  echo $dir
  if [ -d $dir/.svn ];
  then
    echo "$dir is a Subversion repository. Updating."
    sudo svn up $dir
    base=$dir/`cat $dir/install_version`
  fi
  if [ -d $dir/.git ];
  then
    echo "$dir is a git repository. Pulling changes."
    cd $dir
    sudo git checkout master
    sudo git pull
    tag=`cat $dir/install_version`
    sudo git checkout $tag
    base=$dir
  fi
  #InstallDooSoftwareProject $p $base "$dvvers"
done

