#!/bin/bash

packages="DooCore doofit dooselection"

source /lhcbsoft/LHCbSoftwareSetup.sh #> /dev/null 2>&1
export PATH=$PATH:/usr/local/bin

#echo "Probing ROOT versions"
rvers=""
dvvers=""
dvvers_new=""
dvvers_old=""
echo -n "Installing for following DaVinci versions: "
#for ver in `SetupProject.sh DaVinci --list-versions | cut -d " " -f 1`
#do
#  rver=`bash PrintRootVersionForDVVersion $ver`
#  if [[ ! $rvers =~ $rver ]]; then
#    rvers="$rvers $rver"
#    dvvers="$dvvers $ver"
#    echo -n " $ver"
#  fi
#done
#echo ""

dvvers=$(cat /doosoft/dv_versions)
echo $dvvers

dvvers_new=${dvvers%v36r3*}
dvvers_old=${dvvers##*v36r3p1}

echo
echo "Old DaVinci versions are: $dvvers_old"
echo
echo "New DaVinci versions are: $dvvers_new"

for p in $packages; do
  if [[ $p == "DooCore" ]];
  then
    repo="https://github.com/e5-tu-do/$p.git"
  else
    repo="ssh://git@git.e5.physik.tu-dortmund.de:10022/lhcbdoosoftware/$p.git"
  fi
  uuid=`uuidgen -r`
  tmpdir=/tmp/$uuid
  echo
  echo "Cloning $p ($repo) into $tmpdir."
  echo
  git clone $repo $tmpdir
  cd $tmpdir
  if [[ $p == "DooCore" ]];
  then
    tag="v2.10.0"
  elif [[ $p == "doofit" ]];
  then
    tag="v2.31.0"
  elif [[ $p == "dooselection" ]];
  then
    tag="v2.11.0"
  fi
  echo
  echo "Checking out tag $tag of $p."
  echo
  git checkout $tag
  InstallDooSoftwareProject $p $tmpdir "$dvvers_old"
  tag=`cat $tmpdir/install_version`
  echo
  echo "Checking out tag $tag of $p."
  echo
  git checkout $tag
  InstallDooSoftwareProject $p $tmpdir "$dvvers_new"
  cd /
  rm -rf $tmpdir
done

#for p in $packages; do
#  dir=$DOOSOFTROOT/repos/$p
#  echo $dir
#  if [ -d $dir/.svn ];
#  then
#    echo "$dir is a Subversion repository. Updating."
#    sudo svn up $dir
#    base=$dir/`cat $dir/install_version`
#  fi
#  if [ -d $dir/.git ];
#  then
#    echo "$dir is a git repository. Pulling changes."
#    cd $dir
#    sudo git checkout master
#    sudo git pull
#    tag=`cat $dir/install_version`
#    sudo git checkout $tag
#    base=$dir
#  fi
#  InstallDooSoftwareProject $p $base "$dvvers"
#  if [ -d $dir/.git ];
#  then
#    echo "$dir is a git repository. Reverting to master."
#    sudo git checkout master
#  fi
#done

