/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "AtanAcceptance.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(doofit::roofit::functions::AtanAcceptance)

namespace doofit {
namespace roofit {
namespace functions {

long long AtanAcceptance::num_calls_evaluate_ = 0;
long long AtanAcceptance::num_calls_integral_ = 0;


 AtanAcceptance::AtanAcceptance(const char *name, const char *title, 
                        RooAbsReal& _par_x,
                        RooAbsReal& _par_slope_a,
                        RooAbsReal& _par_slope_b) :
   RooAbsReal(name,title), 
   par_x("par_x","par_x",this,_par_x),
   par_slope_a("par_slope_a","par_slope_a",this,_par_slope_a),
   par_slope_b("par_slope_b","par_slope_b",this,_par_slope_b)
 { 
 } 


 AtanAcceptance::AtanAcceptance(const AtanAcceptance& other, const char* name) :  
   RooAbsReal(other,name), 
   par_x("par_x",this,other.par_x),
   par_slope_a("par_slope_a",this,other.par_slope_a),
   par_slope_b("par_slope_b",this,other.par_slope_b)
 { 
 } 

Int_t AtanAcceptance::getAnalyticalIntegral(RooArgSet& ,
                                                       RooArgSet& , const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("AtanAcceptance::getAnalyticalIntegral(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  analVars.Print();
  allVars.Print();
  #endif
  
  //if (matchArgs(allVars, analVars, cat_tag)) return 1;
  
  return 0;
}

} // namespace functions
} // namespace roofit
} // namespace doofit