/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_COMBINATIONOFMISTAGSWITHASYMMETRIES
#define DOOFIT_ROOFIT_FUNCTIONS_COMBINATIONOFMISTAGSWITHASYMMETRIES

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {

class CombinationOfMistagsWithAsymmetries : public RooAbsReal {
public:
  enum TagType {
    kBdType  = +1,
    kBdbType = -1
  };
  
  CombinationOfMistagsWithAsymmetries();
  
  CombinationOfMistagsWithAsymmetries(const char *name, const char *title,
                       RooAbsCategory& _cat_tag_OS,
                       RooAbsReal& _par_tag_p0_OS,
                       RooAbsReal& _par_tag_p1_OS,
                       RooAbsReal& _par_tag_meaneta_OS,
                       RooAbsReal& _par_tag_eta_OS,
                       RooAbsReal& _par_tag_delta_p0_OS,
                       RooAbsReal& _par_tag_delta_p1_OS,
                       RooAbsCategory& _cat_tag_SS,
                       RooAbsReal& _par_tag_p0_SS,
                       RooAbsReal& _par_tag_p1_SS,
                       RooAbsReal& _par_tag_meaneta_SS,
                       RooAbsReal& _par_tag_eta_SS,
                       RooAbsReal& _par_tag_delta_p0_SS,
                       RooAbsReal& _par_tag_delta_p1_SS,
                       TagType _type_tag);
  
  CombinationOfMistagsWithAsymmetries(const CombinationOfMistagsWithAsymmetries& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CombinationOfMistagsWithAsymmetries(*this,newname); }
  inline virtual ~CombinationOfMistagsWithAsymmetries() {
    #ifdef FUNCTIONS_COUNT_CALLS
    std::cout << "CombinationOfMistagsWithAsymmetries::~CombinationOfMistagsWithAsymmetries(): # evaluate calls: " << num_calls_evaluate_ << std::endl;
    std::cout << "CombinationOfMistagsWithAsymmetries::~CombinationOfMistagsWithAsymmetries(): # integral calls: " << num_calls_integral_ << std::endl;
    #endif
  }

protected:

  RooRealProxy par_tag_p0_OS ;
  RooRealProxy par_tag_p1_OS ;
  RooRealProxy par_tag_meaneta_OS ;
  RooRealProxy par_tag_eta_OS ;
  RooRealProxy par_tag_delta_p0_OS ;
  RooRealProxy par_tag_delta_p1_OS ;
  RooRealProxy par_tag_p0_SS ;
  RooRealProxy par_tag_p1_SS ;
  RooRealProxy par_tag_meaneta_SS ;
  RooRealProxy par_tag_eta_SS ;
  RooRealProxy par_tag_delta_p0_SS ;
  RooRealProxy par_tag_delta_p1_SS ;
  
  RooCategoryProxy cat_tag_OS ;
  RooCategoryProxy cat_tag_SS ;
  
  const TagType type_tag ;
  
  static long long num_calls_evaluate_;
  static long long num_calls_integral_;
  
  inline Double_t evaluate() const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_evaluate_;
    #endif
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    
    //std::cout <<  << std::endl;
    
    Double_t omega_OS = par_tag_p0_OS + 0.5*type_tag*par_tag_delta_p0_OS + (par_tag_p1_OS + 0.5*type_tag*par_tag_delta_p1_OS)*(par_tag_eta_OS - par_tag_meaneta_OS);
    Double_t omega_SS = par_tag_p0_SS + 0.5*type_tag*par_tag_delta_p0_SS + (par_tag_p1_SS + 0.5*type_tag*par_tag_delta_p1_SS)*(par_tag_eta_SS - par_tag_meaneta_SS);

    if (cat_tag_OS == cat_tag_SS) {
      return omega_OS*omega_SS/(omega_OS*omega_SS + (1.0-omega_OS)*(1.0-omega_SS));
    }
    else {
      if ((par_tag_p0_SS + par_tag_p1_SS*(par_tag_eta_SS - par_tag_meaneta_SS)) >= (par_tag_p0_OS + par_tag_p1_OS*(par_tag_eta_OS - par_tag_meaneta_OS))) {
        return omega_OS*(1-omega_SS)/(omega_OS*(1.0-omega_SS) + (1.0-omega_OS)*omega_SS);
      }
      else return (1-omega_OS)*omega_SS/(omega_OS*(1.0-omega_SS) + (1.0-omega_OS)*omega_SS);
    }
  }

  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  virtual Int_t	getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName = 0) const;
  
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName = 0) const {
    
    if (1 == code) {
      //std::cout << "CombinationOfMistagsWithAsymmetries::analyticalIntegral(" << code << ", ...): Called." << std::endl;
      return 0.0;
    }
    // must not get here
    //assert(1 == 0);
  }
  
private:

  ClassDef(CombinationOfMistagsWithAsymmetries,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
