/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_COMBINATIONOFCALIBRATEDMISTAGS
#define DOOFIT_ROOFIT_FUNCTIONS_COMBINATIONOFCALIBRATEDMISTAGS

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {

class CombinationOfCalibratedMistags : public RooAbsReal {
public:
  
  CombinationOfCalibratedMistags() {};

  CombinationOfCalibratedMistags(const char *name, const char *title,
                       RooAbsCategory& _cat_tag_OS,
                       RooAbsReal& _par_tag_omega_OS,
                       RooAbsCategory& _cat_tag_SS,
                       RooAbsReal& _par_tag_omega_SS);
  
  CombinationOfCalibratedMistags(const CombinationOfCalibratedMistags& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CombinationOfCalibratedMistags(*this,newname); }
  inline virtual ~CombinationOfCalibratedMistags() {
    #ifdef FUNCTIONS_COUNT_CALLS
    std::cout << "CombinationOfCalibratedMistags::~CombinationOfCalibratedMistags(): # evaluate calls: " << num_calls_evaluate_ << std::endl;
    std::cout << "CombinationOfCalibratedMistags::~CombinationOfCalibratedMistags(): # integral calls: " << num_calls_integral_ << std::endl;
    #endif
  }

protected:

  RooRealProxy par_tag_omega_OS ;
  RooRealProxy par_tag_omega_SS ;
  
  RooCategoryProxy cat_tag_OS ;
  RooCategoryProxy cat_tag_SS ;
  
  static long long num_calls_evaluate_;
  static long long num_calls_integral_;
  
  inline Double_t evaluate() const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_evaluate_;
    #endif
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    
    //std::cout <<  << std::endl;
    
    if (cat_tag_OS == cat_tag_SS) return par_tag_omega_OS*par_tag_omega_SS/(par_tag_omega_OS*par_tag_omega_SS + (1.0-par_tag_omega_OS)*(1.0-par_tag_omega_SS));
    else {
      if (par_tag_omega_SS >= par_tag_omega_OS) {
        return par_tag_omega_OS*(1-par_tag_omega_SS)/(par_tag_omega_OS*(1.0-par_tag_omega_SS) + (1.0-par_tag_omega_OS)*par_tag_omega_SS);
      }
      else return (1-par_tag_omega_OS)*par_tag_omega_SS/(par_tag_omega_OS*(1.0-par_tag_omega_SS) + (1.0-par_tag_omega_OS)*par_tag_omega_SS);
    }
  }

  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  virtual Int_t	getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName = 0) const;
  
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName = 0) const {
    
    if (1 == code) {
      //std::cout << "CombinationOfCalibratedMistags::analyticalIntegral(" << code << ", ...): Called." << std::endl;
      return 0.0;
    }
    // must not get here
    //assert(1 == 0);
  }
  
private:

  ClassDef(CombinationOfCalibratedMistags,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
