/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "CosCoeffWithProdAsymm.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(doofit::roofit::functions::CosCoeffWithProdAsymm)

namespace doofit {
namespace roofit {
namespace functions {

long long CosCoeffWithProdAsymm::num_calls_evaluate_ = 0;
long long CosCoeffWithProdAsymm::num_calls_integral_ = 0;

CosCoeffWithProdAsymm::CosCoeffWithProdAsymm(std::string name,
                                   RooAbsReal& _par_C,
                                   RooAbsReal& _par_omega_Bd,
                                   RooAbsReal& _par_omega_Bdb,
                                   RooAbsCategory& _cat_tag,
                                   RooAbsReal& _par_prod_asym):
  RooAbsReal(name.c_str(), name.c_str()),
  par_C_("par_C_","par_C_",this,_par_C),
  par_omega_Bd_("par_omega_Bd_","par_omega_Bd_",this,_par_omega_Bd),
  par_omega_Bdb_("par_omega_Bdb_","par_omega_Bdb_",this,_par_omega_Bdb),
  cat_tag_("cat_tag_","cat_tag_",this,_cat_tag),
  par_prod_asym_("par_prod_asym_","par_prod_asym_",this,_par_prod_asym)
  {
  }

CosCoeffWithProdAsymm::CosCoeffWithProdAsymm(const CosCoeffWithProdAsymm& other, const char* name) :
  RooAbsReal(other,name),
  par_C_("par_C_",this,other.par_C_),
  par_omega_Bd_("par_omega_Bd_",this,other.par_omega_Bd_),
  par_omega_Bdb_("par_omega_Bdb_",this,other.par_omega_Bdb_),
  cat_tag_("cat_tag_",this,other.cat_tag_),
  par_prod_asym_("par_prod_asym_",this,other.par_prod_asym_)
  {
  }

Int_t CosCoeffWithProdAsymm::getAnalyticalIntegral(RooArgSet& allVars,
                                        RooArgSet& analVars, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("CosCoeffWithProdAsymm::getAnalyticalIntegral(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  //analVars.Print();
  allVars.Print();
  if (rangeName) std::cout << "rangeName: " << rangeName << std::endl;
  #endif
  
  
  return 0;
}


Int_t CosCoeffWithProdAsymm::getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("CosCoeffWithProdAsymm::getAnalyticalIntegralWN(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  //analVars.Print();
  allVars.Print();
  if (normSet) normSet->Print();
  if (rangeName) std::cout << "rangeName: " << rangeName << std::endl;
  #endif
  
  //if (matchArgs(allVars, analVars, cat_tag_)) return 1;
  
  return 0;
}
} // namespace functions
} // namespace roofit
} // namespace doofit

