/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONCOEFFSIN
#define DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONCOEFFSIN

// from STL
#include <string>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

//#define FUNCTIONS_COUNT_CALLS

namespace doofit {
namespace roofit {
namespace functions {

class FunctionCoeffSin : public RooAbsReal {
public:
  enum CoeffType {
    kSType = -1,
    kCType = +1
  };
  
  FunctionCoeffSin();
  FunctionCoeffSin(std::string name,
                   RooAbsReal& _par_S,
                   RooAbsReal& _par_omega,
                   RooAbsCategory& _cat_tag,
                   CoeffType type_coeff);
  
  FunctionCoeffSin(std::string name,
                   RooAbsReal& _par_S,
                   RooAbsReal& _par_tag_p1,
                   RooAbsReal& _par_tag_p0,
                   RooAbsReal& _par_tag_meaneta,
                   RooAbsReal& _par_tag_eta,
                   RooAbsCategory& _cat_tag,
                   CoeffType type_coeff);
  
  FunctionCoeffSin(std::string name,
                   RooAbsReal& _par_S,
                   RooAbsReal& _par_tag_p1,
                   RooAbsReal& _par_tag_p0,
                   RooAbsReal& _par_tag_meaneta,
                   RooAbsReal& _par_tag_delta_p1,
                   RooAbsReal& _par_tag_delta_p0,
                   RooAbsReal& _par_prod_asym,
                   RooAbsReal& _par_tag_eta,
                   RooAbsCategory& _cat_tag,
                   CoeffType type_coeff);
  
  FunctionCoeffSin(const FunctionCoeffSin& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionCoeffSin(*this,newname); }
  inline virtual ~FunctionCoeffSin() {
    #ifdef FUNCTIONS_COUNT_CALLS
    std::cout << "FunctionCoeffSin::~FunctionCoeffSin(): # evaluate calls: " << num_calls_evaluate_ << std::endl;
    std::cout << "FunctionCoeffSin::~FunctionCoeffSin(): # integral calls: " << num_calls_integral_ << std::endl;
    #endif
  }
  
protected:

  RooRealProxy par_S ;
  RooRealProxy par_omega ;
  RooCategoryProxy cat_tag ;
  const CoeffType type_coeff_;
  
  RooRealProxy par_tag_p1_ ;
  RooRealProxy par_tag_p0_ ;
  RooRealProxy par_tag_meaneta_ ;
  RooRealProxy par_tag_eta_ ;
  
  RooRealProxy par_tag_delta_p0_;
  RooRealProxy par_tag_delta_p1_;
  RooRealProxy par_prod_asym_;
  
  const bool per_event_tagging_;
  const bool tagging_asymmetries_;
  
  const double const1_;
  const double const2_;
  
  static long long num_calls_evaluate_;
  static long long num_calls_integral_;
  
  inline Double_t evaluate() const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_evaluate_;
    #endif
    
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
//    ++n_calls;
    // @0*(1-2*@2)*@1
    
    if (per_event_tagging_) {
//      const int tag = cat_tag;
//      double coeff_sin = type_coeff_*cat_tag*(1.0 - 2.0*(par_tag_p1_*(par_tag_eta_-par_tag_meaneta_) + par_tag_p0_))*par_S;
      
      //std::cout << "FunctionCoeffSin::evaluate(): eta = " << par_tag_eta_ << std::endl;
      
      //return cat_tag*par_S*(const2_*par_tag_eta_- + const1_);
      if (tagging_asymmetries_) {
        return type_coeff_*(cat_tag*(1.0 - 2.0*(par_tag_meaneta_+par_tag_p0_ + par_tag_p1_*(par_tag_eta_-par_tag_meaneta_))) - par_prod_asym_*(1.0 - cat_tag*(par_tag_delta_p0_ + par_tag_delta_p1_*(par_tag_eta_-par_tag_meaneta_))))*par_S;
      }
      else return type_coeff_*cat_tag*(1.0 - 2.0*(par_tag_p1_*(par_tag_eta_-par_tag_meaneta_) + par_tag_p0_))*par_S;
    } else {
//      const int tag = cat_tag;
//      double coeff_sin = type_coeff_*tag*(1.0 - 2.0*par_omega)*par_S;
//      
      //std::cout << "FunctionCoeffSin::evaluate(): " << coeff_sin << std::endl;
      
      return type_coeff_*cat_tag*(1.0 - 2.0*par_omega)*par_S ;
    }
  }

  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  virtual Int_t	getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName = 0) const;
  
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName = 0) const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_integral_;
    #endif
    
    //++n_calls;
    //assert(0 != code);
    if (1 == code) {
      //std::cout << "FunctionCoeffSin::analyticalIntegral(" << code << ", ...): Called." << std::endl;
      return 0.0;
    }
    // must not get here
    //assert(1 == 0);
  }
  
//  virtual Double_t getValV(const RooArgSet* nset=0) const {
//    if (nset!=NULL) {
//      nset->Print();
//      return RooAbsReal::getValV(nset);
//    }
//  }

private:

  ClassDef(FunctionCoeffSin,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
