/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FUNCTIONPRODUCT
#define FUNCTIONPRODUCT

// from STL
#include <string>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class FunctionProduct : public RooAbsReal {
public:
  FunctionProduct() {} ; 
  FunctionProduct(std::string name,
	      RooAbsReal& _par_factor1,
	      RooAbsReal& _par_factor2);
  FunctionProduct(const FunctionProduct& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionProduct(*this,newname); }
  inline virtual ~FunctionProduct() {
    std::cout << "FunctionProduct::~FunctionProduct(): num calls " << num_calls_ << std::endl;
  }
  
protected:

  RooRealProxy par_factor1 ;
  RooRealProxy par_factor2 ;
  
  mutable long long num_calls_;
  
  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  inline Double_t evaluate() const {
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    //++num_calls_;
    //std::cout << par_factor1*par_factor2 << std::endl;
    return par_factor1*par_factor2;
  }
  
private:

  ClassDef(FunctionProduct,1) // Your description goes here...
};
 
#endif
