/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_FunctionTripleProduct
#define DOOFIT_ROOFIT_FUNCTIONS_FunctionTripleProduct

// from STL
#include <string>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {

class FunctionTripleProduct : public RooAbsReal {
public:
  FunctionTripleProduct() {};
  FunctionTripleProduct(std::string name,
                  RooAbsReal& _par_factor1,
                  RooAbsReal& _par_factor2,
                  RooAbsReal& _par_factor3);
  
  FunctionTripleProduct(const FunctionTripleProduct& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionTripleProduct(*this,newname); }
  inline virtual ~FunctionTripleProduct() {
//    std::cout << "FunctionTripleProduct::~FunctionTripleProduct(): num calls " << num_calls_ << std::endl;
  }
  
protected:

  RooRealProxy par_factor1 ;
  RooRealProxy par_factor2 ;
  RooRealProxy par_factor3 ;
  
  mutable long long num_calls_;
  
  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  inline Double_t evaluate() const {
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    //++num_calls_;
    return par_factor1*par_factor2*par_factor3;
  }
  
private:

  ClassDef(FunctionTripleProduct,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
