/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FUNCTIONSIMPLESIGNEDTAGGEDCPCOEFFICIENT
#define FUNCTIONSIMPLESIGNEDTAGGEDCPCOEFFICIENT

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {
 
class FunctionSimpleSignedTaggedCPCoefficient : public RooAbsReal {
public:
  FunctionSimpleSignedTaggedCPCoefficient() {} ; 
  FunctionSimpleSignedTaggedCPCoefficient(const char *name, const char *title,
	      RooAbsReal& _mistag_,
	      RooAbsReal& _coeff_,
	      RooAbsReal& _sign_,
	      RooAbsCategory& _tag_);
  FunctionSimpleSignedTaggedCPCoefficient(const FunctionSimpleSignedTaggedCPCoefficient& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionSimpleSignedTaggedCPCoefficient(*this,newname); }
  inline virtual ~FunctionSimpleSignedTaggedCPCoefficient() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy mistag_ ;
  RooRealProxy coeff_ ;
  RooRealProxy sign_ ;
  RooCategoryProxy tag_ ;
  
  Double_t evaluate() const ;

private:

  ClassDef(FunctionSimpleSignedTaggedCPCoefficient,1) // Your description goes here...
};

}
}
}
 
#endif
