/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONSCALEWITHOFFSET
#define DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONSCALEWITHOFFSET

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

//#define FUNCTIONS_COUNT_CALLS

namespace doofit {
namespace roofit {
namespace functions {

class FunctionScaleWithOffset : public RooAbsReal {
public:
  FunctionScaleWithOffset() {} ; 
  FunctionScaleWithOffset(const char *name, const char *title,
	      RooAbsReal& _par_x,
	      RooAbsReal& _par_slope,
	      RooAbsReal& _par_offset);
  FunctionScaleWithOffset(const FunctionScaleWithOffset& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionScaleWithOffset(*this,newname); }
  inline virtual ~FunctionScaleWithOffset() {
    #ifdef FUNCTIONS_COUNT_CALLS
    std::cout << "FunctionScaleWithOffset::~FunctionScaleWithOffset(): # evaluate calls: " << num_calls_evaluate_ << std::endl;
    std::cout << "FunctionScaleWithOffset::~FunctionScaleWithOffset(): # integral calls: " << num_calls_integral_ << std::endl;
    #endif
  }

protected:

  RooRealProxy par_x ;
  RooRealProxy par_slope ;
  RooRealProxy par_offset ;

  static long long num_calls_evaluate_;
  static long long num_calls_integral_;
  
  inline Double_t evaluate() const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_evaluate_;
    #endif
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    
    //std::cout << par_slope*par_x+par_offset << std::endl;
    
    return par_slope*par_x+par_offset;
  }
  
  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  virtual Int_t	getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName = 0) const;


private:

  ClassDef(FunctionScaleWithOffset,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
