/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONPRODUCT
#define DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONPRODUCT

// from STL
#include <string>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {

class FunctionProduct : public RooAbsReal {
public:
  FunctionProduct() ;
  FunctionProduct(std::string name,
                  RooAbsReal& _par_factor1,
                  RooAbsReal& _par_factor2);
  
  FunctionProduct(std::string name,
                  RooAbsReal& _par_factor1,
                  RooAbsReal& _par_factor2,
                  RooAbsReal& _par_factor3);
  
  FunctionProduct(const FunctionProduct& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionProduct(*this,newname); }
  inline virtual ~FunctionProduct() {
    std::cout << "FunctionProduct::~FunctionProduct(): num calls " << num_calls_ << std::endl;
  }
  
protected:

  RooRealProxy par_factor1 ;
  RooRealProxy par_factor2 ;
  RooRealProxy par_factor3 ;
  
  const int num_factors ;
  
  mutable long long num_calls_;
  
  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;
  
  inline Double_t evaluate() const {
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    //++num_calls_;
    if (num_factors == 2) {
      //std::cout << par_factor1*par_factor2 << std::endl;
      return par_factor1*par_factor2;
    }
    if (num_factors == 3) {
      return par_factor1*par_factor2*par_factor3;
    }
  }
  
private:

  ClassDef(FunctionProduct,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
