/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONCOEFFSINH
#define DOOFIT_ROOFIT_FUNCTIONS_FUNCTIONCOEFFSINH

// from STL
#include <string>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

//#define FUNCTIONS_COUNT_CALLS

namespace doofit {
namespace roofit {
namespace functions {

class FunctionCoeffSinh : public RooAbsReal {
public:
  FunctionCoeffSinh() {} ; 
  FunctionCoeffSinh(std::string name,
	      RooAbsReal& _par_sinh);
  FunctionCoeffSinh(const FunctionCoeffSinh& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new FunctionCoeffSinh(*this,newname); }
  inline virtual ~FunctionCoeffSinh() {
    #ifdef FUNCTIONS_COUNT_CALLS
    std::cout << "FunctionCoeffSinh::~FunctionCoeffSinh(): # evaluate calls: " << num_calls_evaluate_ << std::endl;
    std::cout << "FunctionCoeffSinh::~FunctionCoeffSinh(): # integral calls: " << num_calls_integral_ << std::endl;
    #endif
  }

protected:

  RooRealProxy par_sinh ;
  
  static long long num_calls_evaluate_;
  static long long num_calls_integral_;
  
  inline Double_t evaluate() const {
    #ifdef FUNCTIONS_COUNT_CALLS
    ++num_calls_evaluate_;
    #endif
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    return par_sinh ;
  }
  
  virtual Int_t	getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
                                      const char* rangeName = 0) const;

  virtual Int_t	getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName = 0) const;

private:

  ClassDef(FunctionCoeffSinh,1) // Your description goes here...
};
} // namespace functions
} // namespace roofit
} // namespace doofit

#endif
