/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOOFIT_ROOFIT_FUNCTIONS_POLYTEST
#define DOOFIT_ROOFIT_FUNCTIONS_POLYTEST

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h"

namespace doofit {
namespace roofit {
namespace functions {

class PolyTest : public RooAbsPdf {
public:
  PolyTest() {} ; 
  PolyTest(const std::string name,
	      RooAbsReal& _x_,
	      RooAbsReal& _c0_,
	      RooAbsReal& _c1_,
	      RooAbsReal& _c2_,
	      RooAbsReal& _c3_,
        RooAbsReal& _c4_,
        RooAbsReal& _c5_,
        RooAbsReal& _c6_,
        RooAbsReal& _c7_);
  PolyTest(const PolyTest& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PolyTest(*this,newname); }
  inline virtual ~PolyTest() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x_ ;
  RooRealProxy c0_ ;
  RooRealProxy c1_ ;
  RooRealProxy c2_ ;
  RooRealProxy c3_ ;
  RooRealProxy c4_ ;
  RooRealProxy c5_ ;
  RooRealProxy c6_ ;
  RooRealProxy c7_ ;
  
  Double_t evaluate() const ;

private:

  Double_t F1(double x) const;
  Double_t F2(double x) const;
  Double_t F3(double x) const;
  Double_t F4(double x) const;
  Double_t F5(double x) const;


  ClassDef(PolyTest,1) // Your description goes here...
};

}
}
}

#endif
