/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "SinCoeffSimple.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(doofit::roofit::functions::SinCoeffSimple)

namespace doofit {
namespace roofit {
namespace functions {

long long SinCoeffSimple::num_calls_evaluate_ = 0;
long long SinCoeffSimple::num_calls_integral_ = 0;


SinCoeffSimple::SinCoeffSimple() :
  type_coeff_(kCType)
  {
  }

SinCoeffSimple::SinCoeffSimple(std::string name,
                                   RooAbsReal& _par_S,
                                   RooAbsReal& _par_omega,
                                   RooAbsCategory& _cat_tag,
                                   CoeffType type_coeff) :
  RooAbsReal(name.c_str(), name.c_str()),
  par_S_("par_S_","par_S_",this,_par_S),
  par_omega_("par_omega_","par_omega_",this,_par_omega),
  cat_tag_("cat_tag_","cat_tag_",this,_cat_tag),
  type_coeff_(type_coeff)
  {
  } 

SinCoeffSimple::SinCoeffSimple(const SinCoeffSimple& other, const char* name) :
  RooAbsReal(other,name),
  par_S_("par_S_",this,other.par_S_),
  par_omega_("par_omega_",this,other.par_omega_),
  cat_tag_("cat_tag_",this,other.cat_tag_),
  type_coeff_(other.type_coeff_)
  {
  }

Int_t SinCoeffSimple::getAnalyticalIntegral(RooArgSet& allVars,
                                        RooArgSet& analVars, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("SinCoeffSimple::getAnalyticalIntegral(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  //analVars.Print();
  allVars.Print();
  if (rangeName) std::cout << "rangeName: " << rangeName << std::endl;
  #endif
  
  matchArgs(allVars, analVars, cat_tag_);
  
  if (analVars.contains(cat_tag_.arg())) {
    return 1;
  }
  
  return 0;
}


Int_t SinCoeffSimple::getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("SinCoeffSimple::getAnalyticalIntegralWN(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  //analVars.Print();
  allVars.Print();
  if (normSet) normSet->Print();
  if (rangeName) std::cout << "rangeName: " << rangeName << std::endl;
  #endif
  
  //if (matchArgs(allVars, analVars, cat_tag_)) return 1;
  
  return 0;
}
} // namespace functions
} // namespace roofit
} // namespace doofit

