/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "TauCorrectionWithBetaFactor.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(doofit::roofit::functions::TauCorrectionWithBetaFactor)

namespace doofit {
namespace roofit {
namespace functions {

long long TauCorrectionWithBetaFactor::num_calls_evaluate_ = 0;
long long TauCorrectionWithBetaFactor::num_calls_integral_ = 0;

 TauCorrectionWithBetaFactor::TauCorrectionWithBetaFactor(const char *name, const char *title,
                        RooAbsReal& _par_tau,
                        RooAbsReal& _par_beta) :
   RooAbsReal(name,title), 
   par_tau("par_tau","par_tau",this,_par_tau),
   par_beta("par_beta","par_beta",this,_par_beta)
 {
 } 


 TauCorrectionWithBetaFactor::TauCorrectionWithBetaFactor(const TauCorrectionWithBetaFactor& other, const char* name) :
   RooAbsReal(other,name), 
   par_tau("par_tau",this,other.par_tau),
   par_beta("par_beta",this,other.par_beta)
 {
 } 

Int_t TauCorrectionWithBetaFactor::getAnalyticalIntegral(RooArgSet& allVars,
                                               RooArgSet& analVars, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("TauCorrectionWithBetaFactor::getAnalyticalIntegral(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
//  analVars.Print();
  allVars.Print();
  #endif
  
  //if (matchArgs(allVars, analVars, cat_tag)) return 1;
  
  return 0;
}

Int_t TauCorrectionWithBetaFactor::getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars, const RooArgSet* normSet, const char* rangeName) const
{
  #ifdef FUNCTIONS_COUNT_CALLS
  std::printf("TauCorrectionWithBetaFactor::getAnalyticalIntegralWN(): In %s line %u (%s): allVars = ",
              __func__, __LINE__, __FILE__);
  //analVars.Print();
  allVars.Print();
  if (normSet) normSet->Print();
  if (rangeName) std::cout << "rangeName: " << rangeName << std::endl;
  #endif
  
  //if (matchArgs(allVars, analVars, cat_tag)) return 1;
  
  return 0;
}
} // namespace functions
} // namespace roofit
} // namespace doofit
