/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TWOTAGGERMISTAGCALIBRATIONANDCOMBINATION
#define TWOTAGGERMISTAGCALIBRATIONANDCOMBINATION

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
namespace doofit {
namespace roofit {
namespace functions {

class TwoTaggerMistagCalibrationAndCombination : public RooAbsReal {
public:
  TwoTaggerMistagCalibrationAndCombination() {} ; 
  TwoTaggerMistagCalibrationAndCombination(const char *name, const char *title,
	      RooAbsReal& _eta_one_,
	      RooAbsReal& _eta_two_,
	      RooAbsReal& _p0_one_,
	      RooAbsReal& _p0_two_,
	      RooAbsReal& _p1_one_,
	      RooAbsReal& _p1_two_,
	      RooAbsReal& _avg_eta_one_,
	      RooAbsReal& _avg_eta_two_,
	      RooAbsCategory& _tag_one_,
	      RooAbsCategory& _tag_two_);
  TwoTaggerMistagCalibrationAndCombination(const TwoTaggerMistagCalibrationAndCombination& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new TwoTaggerMistagCalibrationAndCombination(*this,newname); }
  inline virtual ~TwoTaggerMistagCalibrationAndCombination() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy eta_one_ ;
  RooRealProxy eta_two_ ;
  RooRealProxy p0_one_ ;
  RooRealProxy p0_two_ ;
  RooRealProxy p1_one_ ;
  RooRealProxy p1_two_ ;
  RooRealProxy avg_eta_one_ ;
  RooRealProxy avg_eta_two_ ;
  RooCategoryProxy tag_one_ ;
  RooCategoryProxy tag_two_ ;
  
  Double_t evaluate() const ;

private:

  ClassDef(TwoTaggerMistagCalibrationAndCombination,1) // Your description goes here...
};

}
}
}
 
#endif
