/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TWOTAGGERMISTAGCOMBINATION
#define TWOTAGGERMISTAGCOMBINATION

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
namespace doofit {
namespace roofit {
namespace functions {

class TwoTaggerMistagCombination : public RooAbsReal {
public:
  TwoTaggerMistagCombination() {} ; 
  TwoTaggerMistagCombination(const char *name, const char *title,
	      RooAbsReal& _eta_one_,
	      RooAbsReal& _eta_two_,
	      RooAbsCategory& _tag_one_,
	      RooAbsCategory& _tag_two_);
  TwoTaggerMistagCombination(const TwoTaggerMistagCombination& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new TwoTaggerMistagCombination(*this,newname); }
  inline virtual ~TwoTaggerMistagCombination() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy eta_one_ ;
  RooRealProxy eta_two_ ;
  RooCategoryProxy tag_one_ ;
  RooCategoryProxy tag_two_ ;
  
  Double_t evaluate() const ;

private:

  ClassDef(TwoTaggerMistagCombination,1) // Your description goes here...
};

}
}
}
 
#endif
