/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOAPOLLONIOS
#define ROOAPOLLONIOS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooApollonios : public RooAbsPdf {
public:
  RooApollonios() {} ; 
  RooApollonios(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _b,
	      RooAbsReal& _a,
	      RooAbsReal& _n);
  RooApollonios(const RooApollonios& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooApollonios(*this,newname); }
  inline virtual ~RooApollonios() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy b ;
  RooRealProxy a ;
  RooRealProxy n ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooApollonios,1) // Your description goes here...
};
 
#endif
