/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOGENERALIZEDHYPERBOLIC
#define ROOGENERALIZEDHYPERBOLIC

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooGeneralizedHyperbolic : public RooAbsPdf {
public:
  RooGeneralizedHyperbolic() {} ; 
  RooGeneralizedHyperbolic(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _l,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
	      RooAbsReal& _delta,
	      RooAbsReal& _mu);
  RooGeneralizedHyperbolic(const RooGeneralizedHyperbolic& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooGeneralizedHyperbolic(*this,newname); }
  inline virtual ~RooGeneralizedHyperbolic() { }

protected:

  RooRealProxy x ;
  RooRealProxy l ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  RooRealProxy delta ;
  RooRealProxy mu ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooGeneralizedHyperbolic,1) // Your description goes here...
};
 
#endif
