/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooLogGamma.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooLogGamma) 

 RooLogGamma::RooLogGamma(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _nu,
                        RooAbsReal& _landa,
                        RooAbsReal& _alpha) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   nu("nu","nu",this,_nu),
   landa("landa","landa",this,_landa),
   alpha("alpha","alpha",this,_alpha)
 { 
 } 


 RooLogGamma::RooLogGamma(const RooLogGamma& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   nu("nu",this,other.nu),
   landa("landa",this,other.landa),
   alpha("alpha",this,other.alpha)
 { 
 } 



 Double_t RooLogGamma::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t xi = (x-nu)/landa;
   Double_t thingie = alpha*xi - exp(xi);
   return exp(thingie) ; 
 } 



