/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOREPARAMGHYP
#define ROOREPARAMGHYP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooReparamGHYP : public RooAbsPdf {
public:
  RooReparamGHYP() {} ; 
  RooReparamGHYP(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _l,
	      RooAbsReal& _zeta,
	      RooAbsReal& _fb,
	      RooAbsReal& _sigma,
	      RooAbsReal& _mu);
  RooReparamGHYP(const RooReparamGHYP& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooReparamGHYP(*this,newname); }
  inline virtual ~RooReparamGHYP() { }

protected:

  RooRealProxy x ;
  RooRealProxy l ;
  RooRealProxy zeta ;
  RooRealProxy fb ;
  RooRealProxy sigma ;
  RooRealProxy mu ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooReparamGHYP,1) // Your description goes here...
};
 
#endif
