/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

#include "Riostream.h" 

#include "CubicSplinePdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(doofit::roofit::pdfs::CubicSplinePdf) 

namespace doofit {
namespace roofit {
namespace pdfs {

 CubicSplinePdf::CubicSplinePdf(const std::string name, 
                        RooRealVar& _x_,
                        std::vector<double>& _knots_, 
                        RooArgList& _coefList_,
                        double _max_range_) :
   RooAbsPdf(name.c_str(),name.c_str()), 
   x_("x_","x_",this,_x_),
   cubic_spline_fun_("cubic_spline_fun_", "cubic_spline_fun_", _x_, _knots_, _coefList_),
   max_range_(_max_range_)
 { 
 } 


 CubicSplinePdf::CubicSplinePdf(const CubicSplinePdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x_("x_",this,other.x_),
   cubic_spline_fun_(other.cubic_spline_fun_),
   max_range_(other.max_range_)
 { 
 } 


 Double_t CubicSplinePdf::evaluate() const 
 { 
   if ( (x_ >= 0.0) && (x_ <= max_range_) ){
      return cubic_spline_fun_.getVal();
   }
   else{
      return 0;
   }
 } 



 Int_t CubicSplinePdf::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   // if (matchArgs(allVars,analVars,x)) return 1 ; 
   return 0 ; 
 } 



 Double_t CubicSplinePdf::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   // assert(code==1) ; 
   // return (x.max(rangeName)-x.min(rangeName)) ; 
   return 0 ; 
 } 

}
}
}

