/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEFFICIENCYBIN
#define ROOEFFICIENCYBIN

#include <vector>

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooEfficiencyBin : public RooAbsReal {
public:
   
   RooEfficiencyBin() {} ; 
   RooEfficiencyBin(const char *name, const char *title);
   RooEfficiencyBin(const char *name, const char *title,
                    const std::map<RooAbsReal*, bool>& variables);
   RooEfficiencyBin(const RooEfficiencyBin& other, const char* name = 0);
   virtual TObject* clone(const char* newname) const
   {
      return new RooEfficiencyBin(*this, newname);
   }

   virtual void addEntry(RooAbsReal*, bool);

   virtual ~RooEfficiencyBin();

protected:

   Double_t evaluate() const ;

private:

   std::map<RooRealProxy*, bool> _variables;

   ClassDef(RooEfficiencyBin,1) // Your description goes here...
};
 
#endif
