/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOREALCATEGORY
#define ROOREALCATEGORY

#include "RooAbsReal.h"
#include "RooCategoryProxy.h"
 
class RooRealCategory : public RooAbsReal {
public:
  RooRealCategory() {} ; 
  RooRealCategory(const char *name, const char *title, RooAbsCategory& _c);
  RooRealCategory(const RooRealCategory& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRealCategory(*this,newname); }
  inline virtual ~RooRealCategory() { }

private:

  RooCategoryProxy c ;
  
  Double_t evaluate() const ;

  ClassDef(RooRealCategory,1)
};
 
#endif
